# Generated by Django 6.0.4 on 2026-05-01 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram')),
                ('whatsapp', models.CharField(blank=True, max_length=100, null=True, verbose_name='WhatsApp')),
                ('viber', models.CharField(blank=True, max_length=100, null=True, verbose_name='Viber')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер')),
            ],
        ),
        migrations.CreateModel(
            name='CallTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_at', models.DateTimeField(verbose_name='Когда позвонить')),
                ('status', models.CharField(choices=[('PLANNED', 'Запланирован'), ('DONE', 'Выполнен')], default='PLANNED', max_length=20, verbose_name='Статус')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_tasks', to='crm.client', verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('CALL', 'Звонок'), ('NOTE', 'Заметка'), ('TRANSFER', 'Передача клиента')], default='NOTE', max_length=20, verbose_name='Тип записи')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_notes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.client', verbose_name='Клиент')),
            ],
        ),
    ]
