# Generated by Django 6.0.4 on 2026-05-04 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_client_viber_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('CLIENT', 'Клиент'), ('MANAGER', 'Менеджер')], max_length=20, verbose_name='Отправитель')),
                ('channel', models.CharField(choices=[('TELEGRAM', 'Telegram')], default='TELEGRAM', max_length=20, verbose_name='Канал')),
                ('external_id', models.CharField(blank=True, help_text='ID пользователя в Telegram (или другом канале)', max_length=255, null=True, verbose_name='Внешний ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время сообщения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.client', verbose_name='Клиент')),
            ],
        ),
    ]
