# Generated by Django 6.0.4 on 2026-05-06 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_clientmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.EmailField(max_length=255, verbose_name='От кого (email)')),
                ('subject', models.CharField(blank=True, max_length=500, null=True, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Текст письма')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Получено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='crm.client', verbose_name='Клиент')),
            ],
        ),
    ]
