# Generated by Django 6.0.4 on 2026-05-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_clientemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemail',
            name='direction',
            field=models.CharField(choices=[('IN', 'Входящее'), ('OUT', 'Исходящее')], default='IN', max_length=3, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='clientemail',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Получено/отправлено'),
        ),
    ]
