# Generated by Django 6.0.5 on 2026-05-07 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_notification_options_alter_notification_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('OUT', 'Исходящий'), ('IN', 'Входящий')], default='OUT', max_length=10, verbose_name='Тип звонка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало звонка')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание звонка')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (сек)')),
                ('recording', models.FileField(blank=True, null=True, upload_to='call_recordings/', verbose_name='Запись разговора')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки по звонку')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='crm.client', verbose_name='Клиент')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог звонка',
                'verbose_name_plural': 'Логи звонков',
                'ordering': ['-created_at'],
            },
        ),
    ]
