# Generated by Django 6.0.5 on 2026-05-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_calllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='uis_recording_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на запись UIS'),
        ),
    ]
