# Generated by Django 6.0.5 on 2026-05-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_calllog_uis_recording_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='uis_call_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID звонка в UIS'),
        ),
    ]
