# Generated by Django 6.0.5 on 2026-05-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_calllog_uis_call_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltask',
            name='task_type',
            field=models.CharField(choices=[('CALL', 'Звонок'), ('EMAIL', 'Письмо'), ('MESSAGE', 'Сообщение'), ('MEETING', 'Встреча')], default='CALL', max_length=20, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='calltask',
            name='planned_at',
            field=models.DateTimeField(verbose_name='Когда выполнить'),
        ),
    ]
