# Generated by Django 6.0.5 on 2026-05-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_calltask_task_type_alter_calltask_planned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientnote',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалена'),
        ),
        migrations.AddField(
            model_name='clientnote',
            name='meta_type',
            field=models.CharField(choices=[('ENTRY', 'Обычная запись'), ('SYSTEM', 'Системное событие')], default='ENTRY', help_text='ENTRY — обычная запись, SYSTEM — служебное событие (email, изменения заметок и т.п.)', max_length=20, verbose_name='Тип записи (служебный)'),
        ),
        migrations.AddField(
            model_name='clientnote',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='Закреплена'),
        ),
        migrations.AlterField(
            model_name='clientnote',
            name='note_type',
            field=models.CharField(choices=[('CALL', 'Звонок'), ('NOTE', 'Заметка'), ('TRANSFER', 'Передача клиента'), ('EMAIL', 'Email'), ('SYSTEM', 'Системное событие')], default='NOTE', max_length=20, verbose_name='Тип записи'),
        ),
    ]
