# Generated by Django 6.0.5 on 2026-05-10 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_clientnote_is_deleted_clientnote_meta_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='preferred_contact',
            field=models.CharField(blank=True, choices=[('PHONE', 'Телефон'), ('EMAIL', 'Email'), ('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp')], max_length=20, null=True, verbose_name='Приоритетный тип связи'),
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('PHONE', 'Телефон'), ('EMAIL', 'Email'), ('TELEGRAM', 'Telegram'), ('WHATSAPP', 'WhatsApp'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='Тип контакта')),
                ('value', models.CharField(max_length=255, verbose_name='Контакт')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_contacts', to='crm.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Дополнительный контакт',
                'verbose_name_plural': 'Дополнительные контакты',
                'ordering': ['created_at'],
            },
        ),
    ]
