# Generated by Django 6.0.5 on 2026-05-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_client_preferred_contact_clientcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('BUYER', 'Покупатель'), ('BUILDER', 'Строитель')], default='BUYER', max_length=20, verbose_name='Тип клиента'),
        ),
        migrations.AddField(
            model_name='client',
            name='pipeline_stage',
            field=models.CharField(blank=True, choices=[('B_COLD', 'Холодный контакт (покупатель)'), ('B_NEEDS', 'Выявление потребности (покупатель)'), ('B_OFFER', 'Предложение (покупатель)'), ('B_PAYMENT', 'Оплата (покупатель)'), ('B_DELIVERY', 'Исполнение (покупатель)'), ('BU_COLD', 'Холодный контакт (строитель)'), ('BU_CONTACT', 'Контакт (строитель)'), ('BU_TASKS', 'Выявление задач (строитель)'), ('BU_KP', 'КП (строитель)'), ('BU_FIRST_CONTRACT', 'Первый договор (строитель)'), ('BU_SUPPORT', 'Сопровождение и удержание (строитель)')], max_length=30, null=True, verbose_name='Этап воронки'),
        ),
    ]
