# Generated by Django 6.0.5 on 2026-05-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_client_client_type_client_pipeline_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='dialed_number',
            field=models.CharField(blank=True, help_text='Номер, по которому фактически звонят (основной или доп.)', max_length=100, null=True, verbose_name='Набранный номер'),
        ),
    ]
