# Generated by Django 6.0.5 on 2026-05-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_calllog_dialed_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='first_note',
            field=models.TextField(blank=True, help_text='Подробное примечание при создании клиента', null=True, verbose_name='Примечание при создании'),
        ),
        migrations.AddField(
            model_name='client',
            name='request_text',
            field=models.CharField(blank=True, help_text='Краткий запрос клиента', max_length=500, null=True, verbose_name='Запрос'),
        ),
        migrations.AddField(
            model_name='client',
            name='source',
            field=models.CharField(blank=True, help_text='Откуда пришёл клиент (реклама, рекомендация и т.п.)', max_length=255, null=True, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('EMAIL', 'Новое письмо'), ('TRANSFER', 'Передача клиента'), ('SYSTEM', 'Системное событие')], max_length=20, verbose_name='Тип уведомления'),
        ),
    ]
