# Generated by Django 6.0.5 on 2026-05-20 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_internalmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='internal_attachments/%Y/%m/%d/', verbose_name='Файл')),
                ('original_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.internalmessage', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Вложение внутреннего сообщения',
                'verbose_name_plural': 'Вложения внутренних сообщений',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
